# Site information
site_name: "RIME List & Docs"
site_url: https://hantang.github.io/rime-docs/
# site_author: hantang
# site_description: "all things about rime"
copyright: Copyleft &copy; 2024
# docs_dir: docs/

# Repository
repo_name: rime-docs
repo_url: https://github.com/hantang/rime-docs/
# edit_uri: tree/main

# Theme
theme:
  name: material
  # custom_dir: overrides
  favicon: static/favicon.png
  logo: static/favicon.png
  language: "zh"
  icon:
    logo: material/keyboard
    repo: fontawesome/brands/square-github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  font:
    text: Open Sans, Helvetica Neue, Roboto, sans-serif, serif
    code: Fira Mono, Fira Code, Roboto Mono, monospace
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.expand
    # - navigation.sections
    # - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    # - search.share
    - toc.follow
    # - toc.integrate
    - content.code.copy
    # - content.action.edit
    # - content.action.view
    - header.autohide

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums_style: pymdownx-inline
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.pathconverter
  # more
  - mdx_truly_sane_lists
  # - markdown_gfm_admonition
  # - mdx_wikilink_plus

extra_javascript:
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/src/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/sorts/tablesort.date.min.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/sorts/tablesort.number.min.js
  - static/js/tablesort.js

# extra_css:
#   - static/css/extra.css

plugins:
  - search
      # lang:
      #   - en
      #   - zh
      # separator: '[\s\-,:!=\[\]()"/\u200b]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - table-reader
  - awesome-pages:
      collapse_single_pages: true
      strict: false
      # order: asc
      # sort_type: natural
      # order_by: title
  # - minify:
  #     minify_html: true
  # - i18n:
  #     docs_structure: suffix
  #     languages:
  #       - locale: zh
  #         default: true
  #         name: 简体中文
  #         build: true
  #       - locale: zh-Hant
  #         name: 繁體中文
  #         build: true
  #         nav_translations:
  #           主页: 主頁
  #           列表: 列表
  #           文档: 文檔
  #           介绍: 介紹
  #           基础: 基礎
  #           发行版: 發行版
  #           macOS-鼠须管: macOS-鼠須管
  #           Windows-小狼毫: windows-小狼毫
  #           Linux-中州韵: Linux-中州韻
  #           进阶: 進階
  #           更多: 更多
  #           博客: 網誌
  #           杂项: 雜項
  #           正式版: 正式版
  #           测试版: 測試版
  #           发布: 發佈
  #       - locale: en
  #         name: English
  #         build: true
  #         # site_name:
  #         nav_translations:
  #           主页: Home
  #           列表: List
  #           文档: Wiki
  #           介绍: Introduction
  #           基础: Basic
  #           发行版: Distribution
  #           macOS-鼠须管: macOS-Squirrel
  #           Windows-小狼毫: Windows-Weasel
  #           Linux-中州韵: Linux-Rime
  #           进阶: Advanced
  #           更多: More
  #           博客: Blog
  #           杂项: Misc
  #           正式版: Release Version
  #           测试版: Testing Version
  #           发布: Release
  # - git-revision-date-localized

# exclude_docs: |
#   /drafts/

nav:
  - 主页:
    - index.md
    - list.md
  - 博客:
      - ... | flat | blog/posts/*.md
  - 文档:
    - wiki/index.md
    - 介绍:
      - wiki/Introduction.md
      - wiki/Downloads.md
      - blog/download/index.md
      - wiki/FAQ.md
      - blog/docs/index.md
      - wiki/MoodCollection.md
      - wiki/UserQuotes.md
    - 基础:
      - wiki/GettingStarted.md
      - wiki/UserGuide.md
      - wiki/RimeWithTheDesign.md
      - wiki/UserData.md
      - wiki/SharedData.md
      - wiki/CustomizationGuide.md
    - 进阶:
      - wiki/Configuration.md
      - wiki/RimeWithSchemata.md
      - collect/RimeDescription-Schema.md
      - collect/RimeDescription-Dict.md
      - wiki/DictionaryPack.md
      - wiki/Recipes.md
      - wiki/RimeWithTheCode.md
      - blog/code/index.md
      - blog/i-rime-with-fool/index.md
      - wiki/SpellingAlgebra.md
      - wiki/Rime-in-Emacs.md
  - 版本:
    - Linux-中州韵:
      - linux/index.md
      - linux/CHANGELOG.md
      - wiki/RimeWithIBus.md
      - linux/fcitx5/index.md
    - Windows-小狼毫:
      - windows/index.md
      - windows/INSTALL.md
      - windows/CHANGELOG.md
      - wiki/RimeWithWeasel.md
      - wiki/WeaselReleaseManual.md
      - windows/weasel/Home.md
      - windows/weasel/Installation.md
      - windows/weasel/Customization.md
      - windows/weasel/Example.md
      - windows/weasel/Theme.md
      - windows/weasel/ColorSchemes.md
      - windows/weasel/Font.md
      - windows/weasel/Cheatsheet.md
    - macOS-鼠须管:
      - macos/index.md
      - macos/INSTALL.md
      - macos/CHANGELOG.md
      - collect/SquirrelGuide.md
      - wiki/RimeWithSquirrel.md
      - wiki/SquirrelReleaseManual.md
      - macos/squirrel/Home.md
      - macos/squirrel/Customization.md
      - macos/squirrel/FindFontname.md
      - macos/squirrel/UseFontSourceHan.md
      - macos/squirrel/Shortcut.md
      - macos/squirrel/SwitchInputMethod.md
      - macos/squirrel/SwitchLanguage.md
    - Android
    - iOS

  - 更多:
    - wiki/ComboPinyin.md
    - collect/OldCantonese.md
    # - ...
